name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
      # - 'at/test-ci-reusable'
    paths-ignore:
      - 'docs/**'
jobs:
  tests:
    name: "Tests"
    uses: "SciML/.github/.github/workflows/CI.yml@at/reusable-ci-workflow"
    with:
      group: 'Core'
      checkout-ref: "c7d22a663e0097173a847051ad1bdc14bd07ea40"
    secrets: "inherit"

