name: Documentation

on:
  push:
    branches:
      - master
      - 'release-'
      - 'at/test-ci-reusable'
    tags: '*'
  pull_request:

jobs:
  build-and-deploy-docs:
    name: "Documentation - Build and Deploy"
    uses: "SciML/.github/.github/workflows/documentation.yml@test"
