name: format-check

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  format-check:
    name: "Open format PR"
    uses: "SciML/.github/.github/workflows/format-check.yml@at/debug-format-workflow"
