name: "Format Check"

on:
  push:
    branches:
      - 'master'
      - 'release-'
      - 'at/test-concurrency'
    tags: '*'
  pull_request:




    
jobs:
  format-check:
    name: "Format Checks"
    uses: "SciML/.github/.github/workflows/format-check.yml@at/test-concurrency"
