name: "Format Check"

on:
  push:
    branches:
      - 'master'
      - 'release-'
      - 'at/test-ci-reusable'
    tags: '*'
  pull_request:

jobs:
  format-check:
    name: "Format Checks"
    uses: "SciML/.github/.github/workflows/format-suggestions-on-pr.yml@test"
    