name: "Tests"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
      - "test-workflow"
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  tests:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
        os:
          - "ubuntu-latest"
    uses: "SciML/.github/.github/workflows/tests.yml@test"
    with:
      julia-version: "${{ matrix.version }}"
      os: "${{ matrix.os }}"
    secrets: "inherit"
